name: Scrape latest

on:
    push:
    pull_request:
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [16.x]

        steps:
            - uses: actions/checkout@v2

            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node-version }}

            - name: Cache multiple paths
              uses: actions/cache@v2
              with:
                  path: |
                      **/node_modules
                  key: ${{ runner.os }}-${{ hashFiles('**/lockfiles') }}

            - name: Install dependencies
              run: npm i

            - name: Fetch latest data
              run: npm run start

            - name: Commit and push if it changed
              run: |-
                  git config user.name "Automated"
                  git config user.email "actions@users.noreply.github.com"
                  git add -A
                  timestamp=$(date -u)
                  git commit -m "Latest data: ${timestamp}" || exit 0
                  git push